### ISSUE TITLE
Error Pushing Packages to Expo

### ISSUE THREAD

**Issue by DoubleOTheven** [FormidableLabs/appr#13]
After the latest release `a2520e3d97f08356b950fc29558dc4c49615736` I'm getting an error. 

Running on Travis on OSX:

```
[exp] Invalid Version: undefined
[exp] TypeError: Invalid Version: undefined
    at new SemVer (/Users/travis/build/companyApp/company-ui/node_modules/semver/semver.js:279:11)
    at Function.major (/Users/travis/build/companyApp/company-ui/node_modules/semver/semver.js:551:10)
    at /xdl/src/project/Doctor.js:629:18
    at /Users/travis/build/companyApp/company-ui/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/Users/travis/build/companyApp/company-ui/node_modules/lodash/lodash.js:3001:24)
    at /Users/travis/build/companyApp/company-ui/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/Users/travis/build/companyApp/company-ui/node_modules/lodash/lodash.js:9359:14)
    at /xdl/src/project/Doctor.js:619:9
    at Generator.throw (<anonymous>)
    at step (/Users/travis/build/companyApp/company-ui/node_modules/exp/node_modules/xdl/build/project/Doctor.js:615:191)
    at /Users/travis/build/companyApp/company-ui/node_modules/exp/node_modules/xdl/build/project/Doctor.js:615:402
    at <anonymous>
/Users/travis/build/companyApp/company-ui/node_modules/appr/index.js:22
      throw new Error('Failed to publish package to Expo');
      ^
Error: Failed to publish package to Expo
    at publishError (/Users/travis/build/companyApp/company-ui/node_modules/appr/index.js:22:13)
    at ChildProcess.child.on.code (/Users/travis/build/companyApp/company-ui/node_modules/appr/scripts/spawn.js:16:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn appr" exited with 1.
cache.2
store build cache
```

**Comment by jevakallio** [comment]
Can you share you package.json and app.json? Cannot replicate in any of my projects, running Travis on Linux.

**Comment by DoubleOTheven** [comment]
@jevakallio 

package.json:
```
{
  "name": "foo",
  "version": "0.1.0",
  "private": true,
  "license": "UNLICENSED",
  "devDependencies": {
    "@storybook/addon-actions": "3.2.16",
    "@storybook/addon-links": "3.2.16",
    "@storybook/react-native": "3.2.16",
    "appr": "^1.1.0",
    "axios-mock-adapter": "1.10.0",
    "babel-eslint": "8.0.2",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "eslint": "4.11.0",
    "eslint-config-airbnb": "16.1.0",
    "eslint-import-resolver-babel-module": "4.0.0-beta.3",
    "eslint-plugin-import": "2.8.0",
    "eslint-plugin-jsx-a11y": "6.0.2",
    "eslint-plugin-react": "7.5.1",
    "eslint-restricted-globals": "0.1.1",
    "jest-expo": "23.0.0",
    "react-dom": "16.1.1",
    "react-native-dotenv": "0.1.0",
    "react-native-scripts": "1.7.0",
    "react-test-renderer": "16.1.1"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "android": "react-native-scripts android",
    "appr": "appr",
    "eject": "react-native-scripts eject",
    "ios": "react-native-scripts ios",
    "lint": "./node_modules/.bin/eslint *.js ./app/**/*.js ./app/**/**/*.js ./app/**/**/**/*.js ./app/**/**/**/**/*.js",
    "start": "react-native-scripts start",
    "storybook": "storybook start -p 7007",
    "setupTravis": "node setupTravis.js",
    "test": "node node_modules/jest/bin/jest.js --watch",
    "testSingleRun": "node node_modules/jest/bin/jest.js"
  },
  "jest": {
    "preset": "jest-expo",
    "collectCoverageFrom": [
      "app/common/stores/**/tests/*.js",
      "app/common/components/**/tests/*.js"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!react-native|react-navigation)/"
    ]
  },
  "dependencies": {
    "axios": "0.17.1",
    "babel-core": "6.26.0",
    "babel-plugin-module-resolver": "3.0.0",
    "base-64": "0.1.0",
    "expo": "23.0.2",
    "mobx": "3.3.2",
    "mobx-persist": "0.4.1",
    "mobx-react": "4.3.5",
    "moment": "2.19.2",
    "prop-types": "15.6.0",
    "react": "16.1.1",
    "react-native": "0.50.4",
    "react-native-checkbox": "2.0.0",
    "react-native-iphone-x-helper": "1.0.1",
    "react-native-loading-spinner-overlay": "0.5.2",
    "react-native-modalbox": "1.4.2",
    "react-native-progress": "3.4.0",
    "react-native-svg": "5.5.1",
    "react-navigation": "https://github.com/bar/react-navigation",
    "utf8": "2.1.2"
  }
}
```

app.json:
```
{
  "name": "foo",
  "displayName": "foo",
  "privacy": "unlisted",
  "expo": {
    "sdkVersion": "23.0.0",
    "orientation": "portrait",
    "primaryColor": "#000000",
    "icon": "./app/common/images/logoSquare.png",
    "androidStatusBarColor": "#000000",
    "loading": {
      "hideExponentText": true
    },
    "notification": {
      "color": "#000000",
      "androidMode": "default",
      "icon": "./app/common/images/notificationIcon.png"
    },
    "ios": {
      "splash": {
        "backgroundColor": "#000000",
        "image": "./app/common/images/splash.png",
        "resizeMode": "cover"
      }
    },
    "android": {
      "splash": {
        "backgroundColor": "#000000",
        "mdpi": "./app/common/images/splash.png",
        "resizeMode": "cover"
      }
    },
    "facebookScheme": "bar"
  }
}
```

**Comment by DoubleOTheven** [comment]
@jevakallio I tried on linux instead of OSX, and still get an error. See the app.json, and package.json above

```
Success. You are now logged in as XXXXXXX
.
[appr] Logged into Expo.
[appr] Preparing project for publish...
[appr] Publishing project into Expo.
[exp]
 
There is a new version of exp available (47.0.0).
You are currently using exp 44.0.0
Run `npm install -g exp` to get the latest version
[exp]
 Unable to find an existing exp instance for this directory, starting a new one...
[exp]
 
Warning: You are using npm version 5.5.1. There may be bugs in this version, use it at your own risk. We recommend version 4.6.1.
[exp]
 
Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.
[exp]
 
Invalid Version: undefined
[exp]
 
TypeError: Invalid Version: undefined
    at new SemVer (/home/travis/build/foobarApp/foobar-ui/node_modules/semver/semver.js:279:11)
    at Function.major (/home/travis/build/foobarApp/foobar-ui/node_modules/semver/semver.js:551:10)
    at /xdl/src/project/Doctor.js:629:18
    at /home/travis/build/foobarApp/foobar-ui/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/home/travis/build/foobarApp/foobar-ui/node_modules/lodash/lodash.js:3001:24)
    at /home/travis/build/foobarApp/foobar-ui/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/home/travis/build/foobarApp/foobar-ui/node_modules/lodash/lodash.js:9359:14)
    at /xdl/src/project/Doctor.js:619:9
    at Generator.throw (<anonymous>)
    at step (/home/travis/build/foobarApp/foobar-ui/node_modules/exp/node_modules/xdl/build/project/Doctor.js:615:191)
    at /home/travis/build/foobarApp/foobar-ui/node_modules/exp/node_modules/xdl/build/project/Doctor.js:615:402
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
/home/travis/build/foobarApp/foobar-ui/node_modules/appr/index.js:22
      throw new Error('Failed to publish package to Expo');
      ^
Error: Failed to publish package 
to Expo
    at publishError (/home/travis/build/foobarApp/foobar-ui/node_modules/appr/index.js:22:13)
    at ChildProcess.child.on.code (/home/travis/build/foobarApp/foobar-ui/node_modules/appr/scripts/spawn.js:16:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
error
 Command failed with exit code 1.
The command "yarn appr" exited with 1.
```

**Comment by jevakallio** [comment]
@Sonblind weeeird, not seeing any major issues in your config. I'll have to try to replicate this locally.

**Comment by DoubleOTheven** [comment]
Hi @jevakallio, Please let me know what you find. I'd love to use this in our workflow. Thanks!
