### ISSUE TITLE
Adding expo-cli breaks appr

### ISSUE THREAD

**Issue by mehdisadeghi** [FormidableLabs/appr#38]
I replaced `exp` with recently released `expo-cli` and it borke appr. Even re-adding `exp` did not help. This is the part of travis log that shows the error:

```
$ appr
[appr] Logging into Expo...
{ Error: spawn ./node_modules/exp/bin/exp.js ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn ./node_modules/exp/bin/exp.js',
  path: './node_modules/exp/bin/exp.js',
  spawnargs: 
   [ 'login',
     '-u',
     '[secure]',
     '-p',
     '[secure]',
     '--non-interactive' ] }
/home/travis/build/hiposfer/hive/node_modules/appr/index.js:13
    throw new Error('Failed to log into Expo');
    ^
Error: Failed to log into Expo
    at loginError (/home/travis/build/hiposfer/hive/node_modules/appr/index.js:13:11)
    at ChildProcess.child.on.code (/home/travis/build/hiposfer/hive/node_modules/appr/scripts/spawn.js:16:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by wawoon** [comment]
I changed 

```
const localExp = './node_modules/exp/bin/exp.js';	
```

to

```
const localExp = './node_modules/expo/bin/cli.js';
```

and add  `expo` and `expo-cli` as dependency.
it's working. But I don't know it's ideal.

https://github.com/ykosaka-welyco/appr/pull/1/files
